<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="GURU APPLICATION TEST SUITE" duration-ms="60668" started-at="2019-03-31T08:39:27Z" finished-at="2019-03-31T08:40:28Z">
    <groups>
    </groups>
    <test name="VerifY Guru Application Login Test" duration-ms="60668" started-at="2019-03-31T08:39:27Z" finished-at="2019-03-31T08:40:28Z">
      <class name="com.qa.guru.testCases.TC01_LoginTest">
        <test-method status="PASS" signature="setUP(java.lang.String)[pri:0, instance:com.qa.guru.testCases.TC01_LoginTest@7cbd213e]" name="setUP" is-config="true" duration-ms="46888" started-at="2019-03-31T08:39:27Z" finished-at="2019-03-31T08:40:14Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUP -->
        <test-method status="FAIL" signature="guruApplicationLoginTest()[pri:0, instance:com.qa.guru.testCases.TC01_LoginTest@7cbd213e]" name="guruApplicationLoginTest" duration-ms="13214" started-at="2019-03-31T08:40:14Z" finished-at="2019-03-31T08:40:28Z">
          <exception class="junit.framework.AssertionFailedError">
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:47)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at com.qa.guru.testCases.TC01_LoginTest.guruApplicationLoginTest(TC01_LoginTest.java:50)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- guruApplicationLoginTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qa.guru.testCases.TC01_LoginTest@7cbd213e]" name="tearDown" is-config="true" duration-ms="165" started-at="2019-03-31T08:40:28Z" finished-at="2019-03-31T08:40:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.qa.guru.testCases.TC01_LoginTest -->
    </test> <!-- VerifY Guru Application Login Test -->
  </suite> <!-- GURU APPLICATION TEST SUITE -->
</testng-results>
